services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    volumes:
      - konyvtar-postgres:/var/lib/postgresql/data
    env_file:
      - .env
  backend:
    build: .
    env_file: ./.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres

volumes:
  konyvtar-postgres:
