services:
  postgres-dev:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    volumes:
      - konyvtar-dev-postgres:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  konyvtar-dev-postgres:
