services:
  postgres:
    image: postgres:17-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - konyvtar-postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - konyvtar-network
  backend:
    build: .
    restart: always
    env_file: .env
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    networks:
      - konyvtar-network

volumes:
  konyvtar-postgres:
networks:
  konyvtar-network:
